Added method getExtraContent
veraPDF/veraPDF-model-syntax pull request #41
Opened 2020-04-24 07:18 UTC by MaximPlusov

2020-05-07 09:28 UTC, carlwilson requested changes

2020-05-07 09:28 UTC, carlwilson commented on org.verapdf.releng/pom.xml
> +							<version>3.10.200</version>
Can we make this a single maven property please so we only change the version in one place, thanks.

2020-05-07 09:28 UTC, carlwilson commented on org.verapdf.tests/pom.xml
> +						<version>3.10.200</version>
See property comment.

2020-05-07 09:28 UTC, carlwilson commented on org.verapdf.ui/pom.xml
> +						<version>3.10.200</version>
and here please :)

2020-05-07 09:28 UTC, carlwilson commented on org.verapdf/pom.xml
> +						<version>3.10.200</version>
once more.

2020-05-07 09:28 UTC, carlwilson commented on .travis.yml
> -  - oraclejdk7
and maybe go openJDK here if possible.

2020-05-07 09:34 UTC, MaximPlusov commented on .travis.yml
> -  - oraclejdk7
openjdk8?

2020-05-07 11:36 UTC, carlwilson reviewed
good stuff

2020-05-08 09:46 UTC, carlwilson approved these changes

2020-05-08 09:46 UTC, merged